### ISSUE TITLE
HealthCheck

### ISSUE THREAD

**Issue by ksuderman** [lappsgrid-incubator/askme-web#6]
Each service should respond to a *PING* message, that is, a message with nothing but the String *PING* as the **command**. The service should respond with a *PONG* messages, a message with nothing but the String *PONG* in the **command** field.  *PING*s can be used to determine if a service is online and responding to messages.

The following service should respond to *PING*s:

- [x] nlp
- [x] query
- [x] solr
- [x] ranking

The web  module will also need to respond to health check requests, but that will be done through the REST API and not RabbitMQ messages.

**Comment by marcverhagen** [comment]
I like that ping-pong stuff, but isn't it already possible to just ask for the metadata to check whether a service is available?

**Comment by ksuderman** [comment]
For LAPPS SOAP services yes, but these are micro-services that make up the AskMe application and do not provide JSON metadata.

**Comment by ksuderman** [comment]
Services now respond to PING messages and pass integration tests.
